server:
  port: 8087

spring:
  application:
    name: StudentService
  security:
    user:
      name: foo
      password: foo

  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root

